run:
  timeout: 5m
  tests: true

linters:
  enable:
    - errcheck      # Check for unchecked errors
    - govet         # Vet examines Go source code
    - ineffassign   # Detect ineffectual assignments
    - staticcheck   # Advanced static analysis
    - unused        # Check for unused code
    - misspell      # Check for misspelled words
    - revive        # Fast, configurable linter
    - gosec         # Security-focused linter
    - bodyclose     # Check HTTP response body is closed
    - noctx         # Detect HTTP requests without context
    - sqlclosecheck # Check SQL rows/statements are closed

issues:

  max-issues-per-linter: 0
  max-same-issues: 0
  new: false

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true
  sort-results: true

version: "2"
